[package]
name = "picocraft"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
hecs = "0.11.0"
noise = "0.9.0"
rand = "0.10.0"
raylib = "5.5.1"
rayon = "1.11.0"
rustc-hash = "2.1.1"
